// Generated automatically by update_translations.py from f:\MdAI\mdai-src\Modules/Loadable/Volumes/Resources/VolumeDisplayPresets.json

QT_TRANSLATE_NOOP("VolumeDisplayPresets", "CT-Bone")
QT_TRANSLATE_NOOP("VolumeDisplayPresets", "Emphasize bone in a CT volume.")
QT_TRANSLATE_NOOP("VolumeDisplayPresets", "CT-Air")
QT_TRANSLATE_NOOP("VolumeDisplayPresets", "Emphasize air in a CT volume.")
QT_TRANSLATE_NOOP("VolumeDisplayPresets", "CT-Brain")
QT_TRANSLATE_NOOP("VolumeDisplayPresets", "View brain CT volume.")
QT_TRANSLATE_NOOP("VolumeDisplayPresets", "CT-Abdomen")
QT_TRANSLATE_NOOP("VolumeDisplayPresets", "View abdominal CT volume.")
QT_TRANSLATE_NOOP("VolumeDisplayPresets", "CT-Lung")
QT_TRANSLATE_NOOP("VolumeDisplayPresets", "View lung CT volume.")
QT_TRANSLATE_NOOP("VolumeDisplayPresets", "PET")
QT_TRANSLATE_NOOP("VolumeDisplayPresets", "Preset for PET volume (uses rainbow color table).")
QT_TRANSLATE_NOOP("VolumeDisplayPresets", "DTI")
QT_TRANSLATE_NOOP("VolumeDisplayPresets", "Preset for DTI scalar volumes like FA (uses rainbow color table).")
